name: Update Markdown Links

on: [push]

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyyaml

    - name: Run link update script
      run: |
        python scripts/update_links.py
      
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Update markdown links'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}